// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/products.proto

package products

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --- Fetch ---
type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_api_proto_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_products_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int32                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"` // сколько создано
	Updated       int32                  `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"` // сколько обновлено
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // если что-то пошло не так
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_api_proto_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_products_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *FetchResponse) GetUpdated() int32 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// --- List ---
type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *PagingParams          `protobuf:"bytes,1,opt,name=paging,proto3" json:"paging,omitempty"`
	Sorting       *SortingParams         `protobuf:"bytes,2,opt,name=sorting,proto3" json:"sorting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_proto_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_products_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetPaging() *PagingParams {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ListRequest) GetSorting() *SortingParams {
	if x != nil {
		return x.Sorting
	}
	return nil
}

type PagingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // номер страницы (1-based)
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // размер страницы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PagingParams) Reset() {
	*x = PagingParams{}
	mi := &file_api_proto_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PagingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagingParams) ProtoMessage() {}

func (x *PagingParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagingParams.ProtoReflect.Descriptor instead.
func (*PagingParams) Descriptor() ([]byte, []int) {
	return file_api_proto_products_proto_rawDescGZIP(), []int{3}
}

func (x *PagingParams) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *PagingParams) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type SortingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`          // "name" или "price"
	Ascending     bool                   `protobuf:"varint,2,opt,name=ascending,proto3" json:"ascending,omitempty"` // true = по возрастанию
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortingParams) Reset() {
	*x = SortingParams{}
	mi := &file_api_proto_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortingParams) ProtoMessage() {}

func (x *SortingParams) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortingParams.ProtoReflect.Descriptor instead.
func (*SortingParams) Descriptor() ([]byte, []int) {
	return file_api_proto_products_proto_rawDescGZIP(), []int{4}
}

func (x *SortingParams) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *SortingParams) GetAscending() bool {
	if x != nil {
		return x.Ascending
	}
	return false
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"` // общее количество (для пагинации)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_api_proto_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_products_proto_rawDescGZIP(), []int{5}
}

func (x *ListResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // в MongoDB обычно string
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_api_proto_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_api_proto_products_proto_rawDescGZIP(), []int{6}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Product) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_api_proto_products_proto protoreflect.FileDescriptor

const file_api_proto_products_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/products.proto\x12\bproducts\" \n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"Y\n" +
	"\rFetchResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\x05R\acreated\x12\x18\n" +
	"\aupdated\x18\x02 \x01(\x05R\aupdated\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"p\n" +
	"\vListRequest\x12.\n" +
	"\x06paging\x18\x01 \x01(\v2\x16.products.PagingParamsR\x06paging\x121\n" +
	"\asorting\x18\x02 \x01(\v2\x17.products.SortingParamsR\asorting\"?\n" +
	"\fPagingParams\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"C\n" +
	"\rSortingParams\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1c\n" +
	"\tascending\x18\x02 \x01(\bR\tascending\"S\n" +
	"\fListResponse\x12-\n" +
	"\bproducts\x18\x01 \x03(\v2\x11.products.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"C\n" +
	"\aProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price2\x81\x01\n" +
	"\x0eProductService\x128\n" +
	"\x05Fetch\x12\x16.products.FetchRequest\x1a\x17.products.FetchResponse\x125\n" +
	"\x04List\x12\x15.products.ListRequest\x1a\x16.products.ListResponseBCZAgithub.com/Vladyslav-Kondrenko/grpc.git/api/proto/gen/go/productsb\x06proto3"

var (
	file_api_proto_products_proto_rawDescOnce sync.Once
	file_api_proto_products_proto_rawDescData []byte
)

func file_api_proto_products_proto_rawDescGZIP() []byte {
	file_api_proto_products_proto_rawDescOnce.Do(func() {
		file_api_proto_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_products_proto_rawDesc), len(file_api_proto_products_proto_rawDesc)))
	})
	return file_api_proto_products_proto_rawDescData
}

var file_api_proto_products_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_products_proto_goTypes = []any{
	(*FetchRequest)(nil),  // 0: products.FetchRequest
	(*FetchResponse)(nil), // 1: products.FetchResponse
	(*ListRequest)(nil),   // 2: products.ListRequest
	(*PagingParams)(nil),  // 3: products.PagingParams
	(*SortingParams)(nil), // 4: products.SortingParams
	(*ListResponse)(nil),  // 5: products.ListResponse
	(*Product)(nil),       // 6: products.Product
}
var file_api_proto_products_proto_depIdxs = []int32{
	3, // 0: products.ListRequest.paging:type_name -> products.PagingParams
	4, // 1: products.ListRequest.sorting:type_name -> products.SortingParams
	6, // 2: products.ListResponse.products:type_name -> products.Product
	0, // 3: products.ProductService.Fetch:input_type -> products.FetchRequest
	2, // 4: products.ProductService.List:input_type -> products.ListRequest
	1, // 5: products.ProductService.Fetch:output_type -> products.FetchResponse
	5, // 6: products.ProductService.List:output_type -> products.ListResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_products_proto_init() }
func file_api_proto_products_proto_init() {
	if File_api_proto_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_products_proto_rawDesc), len(file_api_proto_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_products_proto_goTypes,
		DependencyIndexes: file_api_proto_products_proto_depIdxs,
		MessageInfos:      file_api_proto_products_proto_msgTypes,
	}.Build()
	File_api_proto_products_proto = out.File
	file_api_proto_products_proto_goTypes = nil
	file_api_proto_products_proto_depIdxs = nil
}
